import {
  DocumentData,
  PersonData,
  EpisodeData,
  DefenseLineData,
  LegalComplianceData,
  ChatMessageData,
  DashboardStats,
  ProcessingQueueData,
  SearchResultData,
  GuiltAssessmentData,
} from './case-store'

// ==================== MOCK DOCUMENTS ====================
export const mockDocuments: DocumentData[] = [
  {
    id: 'doc1',
    fileName: 'obvinenie_tom1.pdf',
    originalName: 'Обвинительное заключение - Том 1.pdf',
    fileSize: 2456000,
    mimeType: 'application/pdf',
    extractedText: 'Обвинительное заключение по уголовному делу № 2024-00145 в отношении Колесниченко Д.А. и других лиц по ст. 159 ч.3, 160 ч.2 УК РФ...',
    summary: 'Обвинительное заключение по делу о мошенничестве и присвоении в отношении группы лиц, включая Колесниченко Д.А.',
    documentDate: '2024-03-15',
    documentType: 'обвинение',
    sourceReference: 'том 1, л.д. 1-45',
    processingStatus: 'completed',
    processingError: null,
    uploadedAt: '2024-01-10T08:00:00Z',
    processedAt: '2024-01-10T08:15:00Z',
  },
  {
    id: 'doc2',
    fileName: 'pokazaniya_kolesnichenko.pdf',
    originalName: 'Показания Колесниченко Д.А..pdf',
    fileSize: 890000,
    mimeType: 'application/pdf',
    extractedText: 'Показания обвиняемого Колесниченко Д.А., данные в ходе допроса 15 января 2024 года. Отказываюсь от дачи показаний на основании ст. 51 Конституции РФ...',
    summary: 'Показания обвиняемого Колесниченко, отказ от дачи показаний по ст. 51 Конституции РФ.',
    documentDate: '2024-01-15',
    documentType: 'показание',
    sourceReference: 'том 2, л.д. 10-18',
    processingStatus: 'completed',
    processingError: null,
    uploadedAt: '2024-02-05T10:00:00Z',
    processedAt: '2024-02-05T10:12:00Z',
  },
  {
    id: 'doc3',
    fileName: 'protokol_osmotra.pdf',
    originalName: 'Протокол осмотра места происшествия.pdf',
    fileSize: 1230000,
    mimeType: 'application/pdf',
    extractedText: 'Протокол осмотра служебного помещения ООО "ТехноПром" по адресу: г. Москва, ул. Промышленная, д. 15, оф. 203...',
    summary: 'Протокол осмотра служебного помещения ООО "ТехноПром" - места совершения хищения.',
    documentDate: '2024-01-20',
    documentType: 'протокол',
    sourceReference: 'том 3, л.д. 5-12',
    processingStatus: 'completed',
    processingError: null,
    uploadedAt: '2024-02-15T09:00:00Z',
    processedAt: '2024-02-15T09:20:00Z',
  },
  {
    id: 'doc4',
    fileName: 'finansovyi_audit.pdf',
    originalName: 'Заключение финансового аудита.pdf',
    fileSize: 3100000,
    mimeType: 'application/pdf',
    extractedText: null,
    summary: null,
    documentDate: null,
    documentType: null,
    sourceReference: null,
    processingStatus: 'processing',
    processingError: null,
    uploadedAt: '2024-03-01T14:00:00Z',
    processedAt: null,
  },
  {
    id: 'doc5',
    fileName: 'svidetel_petrov.pdf',
    originalName: 'Показания свидетеля Петрова И.С..pdf',
    fileSize: 560000,
    mimeType: 'application/pdf',
    extractedText: null,
    summary: null,
    documentDate: null,
    documentType: null,
    sourceReference: null,
    processingStatus: 'pending',
    processingError: null,
    uploadedAt: '2024-03-05T16:00:00Z',
    processedAt: null,
  },
  {
    id: 'doc6',
    fileName: 'expertiza_docs.pdf',
    originalName: 'Экспертное заключение № 45/2024.pdf',
    fileSize: 1800000,
    mimeType: 'application/pdf',
    extractedText: null,
    summary: null,
    documentDate: null,
    documentType: null,
    sourceReference: null,
    processingStatus: 'failed',
    processingError: 'Не удалось распознать текст - документ содержит рукописный текст',
    uploadedAt: '2024-03-10T11:00:00Z',
    processedAt: null,
  },
]

// ==================== MOCK PERSONS ====================
export const mockGuiltAssessments: GuiltAssessmentData[] = [
  {
    id: 'ga1',
    personId: 'p1',
    episodeId: 'ep1',
    guiltLevel: 'high',
    evidenceStrength: 'strong',
    forecast: 'Обвинение вероятно будет доказано; вероятность осуждения 85%',
    confidence: 'high',
    mitigating: 'Отсутствие предыдущих судимостей, наличие несовершеннолетнего ребёнка',
    aggravating: 'Особо крупный размер хищения, организатор преступной группы',
    analysisDate: '2024-02-20T10:00:00Z',
    notes: 'Основной подозреваемый, организатор схемы',
  },
  {
    id: 'ga2',
    personId: 'p2',
    episodeId: 'ep1',
    guiltLevel: 'moderate',
    evidenceStrength: 'moderate',
    forecast: 'Вероятность осуждения 60%, возможно переквалификация на менее тяжкую статью',
    confidence: 'moderate',
    mitigating: 'Содействие следствию, признание вины',
    aggravating: 'Участие в организованной группе',
    analysisDate: '2024-02-20T10:00:00Z',
    notes: 'Соучастник, роль второстепенная',
  },
  {
    id: 'ga3',
    personId: 'p3',
    episodeId: 'ep2',
    guiltLevel: 'low',
    evidenceStrength: 'weak',
    forecast: 'Недостаточно доказательств для обвинения',
    confidence: 'moderate',
    mitigating: null,
    aggravating: null,
    analysisDate: '2024-02-20T10:00:00Z',
    notes: 'Косвенное участие, показания противоречивы',
  },
]

export const mockPersons: PersonData[] = [
  {
    id: 'p1',
    fullName: 'Колесниченко Дмитрий Александрович',
    shortName: 'Колесниченко Д.А.',
    role: 'обвиняемый',
    status: 'задержанный',
    description: 'Генеральный директор ООО "ТехноПром", 42 года. Организатор схемы хищения денежных средств.',
    birthDate: '1982-05-15',
    occupation: 'Генеральный директор ООО "ТехноПром"',
    alias: null,
    isKolesnichenko: true,
    defenseStrategy: 'Непризнание вины, отсутствие состава преступления, недоказанность участия',
    guiltLevel: 'high',
    guiltAssessments: [mockGuiltAssessments[0]],
  },
  {
    id: 'p2',
    fullName: 'Сидоров Виктор Петрович',
    shortName: 'Сидоров В.П.',
    role: 'обвиняемый',
    status: 'активный',
    description: 'Финансовый директор ООО "ТехноПром", 38 лет. Соучастник хищения.',
    birthDate: '1986-11-23',
    occupation: 'Финансовый директор',
    alias: 'Виктор П.',
    isKolesnichenko: false,
    defenseStrategy: null,
    guiltLevel: 'moderate',
    guiltAssessments: [mockGuiltAssessments[1]],
  },
  {
    id: 'p3',
    fullName: 'Петров Иван Сергеевич',
    shortName: 'Петров И.С.',
    role: 'свидетель',
    status: 'активный',
    description: 'Бывший сотрудник ООО "ТехноПром", 35 лет. Свидетель по делу.',
    birthDate: '1989-03-07',
    occupation: 'Бухгалтер',
    alias: null,
    isKolesnichenko: false,
    defenseStrategy: null,
    guiltLevel: 'low',
    guiltAssessments: [mockGuiltAssessments[2]],
  },
  {
    id: 'p4',
    fullName: 'Козлова Марина Дмитриевна',
    shortName: 'Козлова М.Д.',
    role: 'потерпевший',
    status: 'активный',
    description: 'Представитель ООО "ИнвестГрупп", потерпевшая сторона по делу о хищении.',
    birthDate: '1990-07-12',
    occupation: 'Юрист ООО "ИнвестГрупп"',
    alias: null,
    isKolesnichenko: false,
    defenseStrategy: null,
    guiltLevel: 'none',
  },
  {
    id: 'p5',
    fullName: 'Иванов Алексей Николаевич',
    shortName: 'Иванов А.Н.',
    role: 'следователь',
    status: 'активный',
    description: 'Следователь СО ОМВД России по г. Москве, старший лейтенант юстиции.',
    birthDate: '1978-09-20',
    occupation: 'Следователь',
    alias: null,
    isKolesnichenko: false,
    defenseStrategy: null,
    guiltLevel: 'none',
  },
]

// ==================== MOCK EPISODES ====================
export const mockEpisodes: EpisodeData[] = [
  {
    id: 'ep1',
    title: 'Эпизод 1: Хищение денежных средств ООО "ТехноПром"',
    description: 'В период с января по декабрь 2023 года Колесниченко Д.А., действуя в составе организованной группы совместно с Сидоровым В.П., совершил хищение денежных средств ООО "ТехноПром" в особо крупном размере путём составления фиктивных договоров и отчётных документов на сумму более 5 млн рублей.',
    date: '2023-01-01/2023-12-31',
    episodeNumber: '1',
    severity: 'особо тяжкое',
    status: 'расследуется',
    persons: [
      { personId: 'p1', involvement: 'органиатор', person: mockPersons[0] },
      { personId: 'p2', involvement: 'соучастник', person: mockPersons[1] },
      { personId: 'p3', involvement: 'свидетель', person: mockPersons[2] },
    ],
    articles: [
      {
        articleId: 'art1',
        article: {
          id: 'art1',
          code: '159 ч.3 УК РФ',
          number: '159',
          codeType: 'УК РФ',
          description: 'Мошенничество, совершенное лицом с использованием своего служебного положения, а равно в крупном размере',
          category: 'тяжкое',
          punishmentMin: 'лишение свободы на срок до 6 лет',
          punishmentMax: 'лишение свободы на срок до 10 лет со штрафом',
          isCurrent: true,
        },
      },
    ],
    locations: [
      {
        locationId: 'loc1',
        location: {
          id: 'loc1',
          name: 'Офис ООО "ТехноПром"',
          address: 'г. Москва, ул. Промышленная, д. 15, оф. 203',
          type: 'место преступления',
          description: 'Служебное помещение, где совершалось хищение',
          coordinates: null,
        },
        context: 'Место совершения преступления - служебное помещение',
      },
    ],
  },
  {
    id: 'ep2',
    title: 'Эпизод 2: Присвоение имущества',
    description: 'Колесниченко Д.А., используя своё служебное положение генерального директора, присвоил имущество ООО "ТехноПром" - компьютерное оборудование и мебель на сумму 500 тыс. рублей.',
    date: '2023-06-15',
    episodeNumber: '2',
    severity: 'средней тяжести',
    status: 'доказано',
    persons: [
      { personId: 'p1', involvement: 'подозреваемый', person: mockPersons[0] },
      { personId: 'p3', involvement: 'свидетель', person: mockPersons[2] },
    ],
    articles: [
      {
        articleId: 'art2',
        article: {
          id: 'art2',
          code: '160 ч.2 УК РФ',
          number: '160',
          codeType: 'УК РФ',
          description: 'Присвоение или растрата, совершенные группой лиц по предварительному сговору',
          category: 'средней тяжести',
          punishmentMin: 'штраф до 300 тыс. рублей',
          punishmentMax: 'лишение свободы на срок до 5 лет',
          isCurrent: true,
        },
      },
    ],
    locations: [
      {
        locationId: 'loc1',
        location: {
          id: 'loc1',
          name: 'Офис ООО "ТехноПром"',
          address: 'г. Москва, ул. Промышленная, д. 15, оф. 203',
          type: 'место преступления',
          description: 'Служебное помещение',
          coordinates: null,
        },
        context: 'Место хранения присвоенного имущества',
      },
    ],
  },
  {
    id: 'ep3',
    title: 'Эпизод 3: Подделка финансовых документов',
    description: 'Сидоров В.П. по указанию Колесниченко Д.А. изготовил и использовал подложные финансовые документы для сокрытия хищения.',
    date: '2023-03-10/2023-11-20',
    episodeNumber: '3',
    severity: 'тяжкое',
    status: 'сомнительно',
    persons: [
      { personId: 'p1', involvement: 'органиатор', person: mockPersons[0] },
      { personId: 'p2', involvement: 'исполнитель', person: mockPersons[1] },
    ],
    articles: [
      {
        articleId: 'art3',
        article: {
          id: 'art3',
          code: '327 ч.2 УК РФ',
          number: '327',
          codeType: 'УК РФ',
          description: 'Подделка, изготовление или оборот поддельных документов, штампов, печатей, бланков',
          category: 'средней тяжести',
          punishmentMin: 'ограничение свободы до 2 лет',
          punishmentMax: 'лишение свободы на срок до 4 лет',
          isCurrent: true,
        },
      },
    ],
    locations: [],
  },
]

// ==================== MOCK DEFENSE LINES ====================
export const mockDefenseLines: DefenseLineData[] = [
  {
    id: 'dl1',
    personId: 'p1',
    strategyType: 'innocence',
    title: 'Отсутствие состава преступления',
    description: 'Действия Колесниченко Д.А. не содержат признаков мошенничества - все финансовые операции были совершены в рамках обычной хозяйственной деятельности компании.',
    evidence: 'Отсутствие фиктивности договоров, наличие реальных поставщиков и исполнителей работ.',
    strength: 'weak',
    probability: '15%',
    articleReferences: 'ст. 159 УК РФ - отсутствие признаков мошенничества',
  },
  {
    id: 'dl2',
    personId: 'p1',
    strategyType: 'procedural_violation',
    title: 'Процессуальные нарушения при расследовании',
    description: 'В ходе расследования были допущены значительные процессуальные нарушения: нарушение сроков расследования, незаконное задержание, нарушение права на защиту.',
    evidence: 'Нарушение сроков предварительного расследования на 45 дней. Задержание без достаточных оснований. Ограничение доступа адвоката к материалам дела.',
    strength: 'moderate',
    probability: '40%',
    articleReferences: 'ст. 6.1 УПК РФ - разумные сроки; ст. 10 УПК РФ - неприкосновенность личности; ст. 49 УПК РФ - право на защиту',
  },
  {
    id: 'dl3',
    personId: 'p1',
    strategyType: 'reclassification',
    title: 'Переквалификация на менее тяжкую статью',
    description: 'Деяние при наличии доказанности должно быть переквалифицировано на ст. 159 ч.1 УК РФ (мошенничество без отягчающих обстоятельств), так как использование служебного положения не доказано.',
    evidence: 'Отсутствие доказательств использования служебного положения для совершения хищения. Размер хищения не соответствует особо крупному.',
    strength: 'moderate',
    probability: '35%',
    articleReferences: 'ст. 159 ч.1 УК РФ - мошенничество без отягчающих обстоятельств',
  },
  {
    id: 'dl4',
    personId: 'p1',
    strategyType: 'lack_of_evidence',
    title: 'Недостаточность доказательств',
    description: 'Доказательства, представленные следствием, insufficient для установления виновности Колесниченко Д.А. в совершении мошенничества.',
    evidence: 'Противоречия в показаниях свидетелей. Отсутствие прямых доказательств участия Колесниченко в составлении фиктивных документов.',
    strength: 'moderate',
    probability: '30%',
    articleReferences: 'ст. 49 Конституции РФ - презумпция невиновности; ст. 307 УПК РФ',
  },
  {
    id: 'dl5',
    personId: 'p1',
    strategyType: 'mitigating',
    title: 'Смягчающие обстоятельства',
    description: 'При признании виновности, наличие значительных смягчающих обстоятельств: отсутствие предыдущих судимостей, несовершеннолетний ребёнок, положительные характеристики.',
    evidence: 'Характеристики с места работы и жительства. Справка о наличии несовершеннолетнего ребёнка. Справка об отсутствии судимостей.',
    strength: 'strong',
    probability: '80%',
    articleReferences: 'ст. 61 УК РФ - смягчающие обстоятельства',
  },
  {
    id: 'dl6',
    personId: 'p1',
    strategyType: 'statute_limitations',
    title: 'Срок давности',
    description: 'Для деяния, предусмотренного ст. 159 ч.1 УК РФ (мошенничество небольшой тяжести), срок давности составляет 2 года. Для переквалифицированного деяния возможное истечение сроков.',
    evidence: 'Если деяние переквалифицировано на ч.1 ст. 159, срок давности истёк.',
    strength: 'weak',
    probability: '10%',
    articleReferences: 'ст. 78 УК РФ - освобождение от уголовной ответственности в связи с истечением сроков давности',
  },
]

// ==================== MOCK COMPLIANCE ====================
export const mockCompliance: LegalComplianceData[] = [
  {
    id: 'lc1',
    documentId: 'doc1',
    articleId: 'art1',
    checkType: 'article_applicability',
    status: 'warning',
    description: 'Статья 159 ч.3 УК РФ применена с превышением - использование служебного положения не доказано, размер хищения требует уточнения.',
    recommendation: 'Переквалифицировать на ст. 159 ч.2 УК РФ или ст. 159 ч.1 УК РФ при недоказанности отягчающих обстоятельств.',
    legalBasis: 'ст. 159 УК РФ, ч.3; Постановление Пленума ВС РФ № 51 от 27.12.2007',
    checkedAt: '2024-02-25T12:00:00Z',
  },
  {
    id: 'lc2',
    documentId: 'doc1',
    articleId: null,
    checkType: 'procedure_compliance',
    status: 'violation',
    description: 'Нарушение сроков предварительного расследования на 45 дней. Нарушение права обвиняемого на защиту - ограничение доступа адвоката.',
    recommendation: 'Заявить ходатайство о возвращении дела прокурору для устранения нарушений (ст. 237 УПК РФ).',
    legalBasis: 'ст. 6.1 УПК РФ, ст. 10 УПК РФ, ст. 49 УПК РФ, ст. 237 УПК РФ',
    checkedAt: '2024-02-25T12:00:00Z',
  },
  {
    id: 'lc3',
    documentId: 'doc2',
    articleId: null,
    checkType: 'evidence_admissibility',
    status: 'compliant',
    description: 'Показания обвиняемого получены с соблюдением процессуальных требований. Отказ от дачи показаний по ст. 51 Конституции РФ зафиксирован правильно.',
    recommendation: null,
    legalBasis: 'ст. 51 Конституции РФ, ст. 47 УПК РФ',
    checkedAt: '2024-02-25T12:05:00Z',
  },
  {
    id: 'lc4',
    documentId: 'doc3',
    articleId: null,
    checkType: 'procedure_compliance',
    status: 'needs_review',
    description: 'Протокол осмотра места происшествия составлен с незначительными процессуальными неточностями: не указано время начала и окончания осмотра.',
    recommendation: 'Дополнить протокол осмотра, указав точное время проведения следственного действия.',
    legalBasis: 'ст. 166 УПК РФ, ст. 180 УПК РФ',
    checkedAt: '2024-02-25T12:10:00Z',
  },
  {
    id: 'lc5',
    documentId: 'doc1',
    articleId: 'art2',
    checkType: 'statute_limitations',
    status: 'warning',
    description: 'Для эпизода по ст. 160 ч.2 УК РФ (средней тяжести) срок давности составляет 6 лет. Эпизод совершён в 2023 году - срок давности не истёк, но необходимо контролировать.',
    recommendation: 'Мониторить сроки давности по каждому эпизоду отдельно.',
    legalBasis: 'ст. 78 УК РФ',
    checkedAt: '2024-02-25T12:15:00Z',
  },
]

// ==================== MOCK CHAT ====================
export const mockChatMessages: ChatMessageData[] = [
  {
    id: 'chat1',
    question: 'Какие статьи УК РФ применены к Колесниченко?',
    answer: 'К Колесниченко Д.А. применены следующие статьи УК РФ:\n\n1. **Ст. 159 ч.3 УК РФ** - Мошенничество, совершённое с использованием служебного положения, в крупном размере (тяжкое преступление, до 10 лет лишения свободы).\n\n2. **Ст. 160 ч.2 УК РФ** - Присвоение или растрата, совершённые группой лиц по предварительному сговору (средней тяжести, до 5 лет).\n\n3. **Ст. 327 ч.2 УК РФ** - Подделка документов (средней тяжести, до 4 лет).\n\n⚠️ **Примечание**: Применение ст. 159 ч.3 может быть оспорено - использование служебного положения не полностью доказано.',
    contextType: 'person_specific',
    contextId: 'p1',
    createdAt: '2024-02-28T10:00:00Z',
  },
  {
    id: 'chat2',
    question: 'Есть ли процессуальные нарушения в деле?',
    answer: 'Анализ материалов дела выявил следующие процессуальные нарушения:\n\n1. **Нарушение сроков расследования** - Срок предварительного расследования превышен на 45 дней (ст. 6.1 УПК РФ).\n\n2. **Нарушение права на защиту** - Ограничение доступа адвоката к материалам дела на этапе ознакомления (ст. 49 УПК РФ).\n\n3. **Незаконное задержание** - Задержание Колесниченко произведено без достаточных оснований, предусмотренных ст. 91 УПК РФ.\n\n4. **Неточности в протоколах** - В протоколе осмотра места происшествия не указано время начала и окончания следственного действия (ст. 166 УПК РФ).\n\n✅ **Рекомендация**: Заявить ходатайство о возвращении дела прокурору для устранения нарушений (ст. 237 УПК РФ).',
    contextType: 'general',
    contextId: null,
    createdAt: '2024-02-28T10:05:00Z',
  },
]

// ==================== MOCK DASHBOARD ====================
export const mockDashboardStats: DashboardStats = {
  totalDocuments: 6,
  processedDocuments: 3,
  totalPersons: 5,
  totalEpisodes: 3,
  totalArticles: 3,
  pendingInQueue: 2,
  guiltDistribution: [
    { level: 'Высокая', count: 1 },
    { level: 'Средняя', count: 1 },
    { level: 'Низкая', count: 1 },
    { level: 'Нет', count: 2 },
  ],
  documentTypeDistribution: [
    { type: 'Обвинение', count: 1 },
    { type: 'Показание', count: 1 },
    { type: 'Протокол', count: 1 },
    { type: 'Другое', count: 3 },
  ],
  recentDocuments: mockDocuments.slice(0, 3),
  processingQueue: [
    {
      id: 'pq1',
      documentId: 'doc4',
      queuePosition: 1,
      status: 'processing',
      startedAt: '2024-03-01T14:10:00Z',
      completedAt: null,
      error: null,
      priority: 3,
      document: mockDocuments[3],
    },
    {
      id: 'pq2',
      documentId: 'doc5',
      queuePosition: 2,
      status: 'queued',
      startedAt: null,
      completedAt: null,
      error: null,
      priority: 5,
      document: mockDocuments[4],
    },
  ],
}

// ==================== MOCK SEARCH ====================
export const mockSearchResults: SearchResultData = {
  documents: mockDocuments.slice(0, 2),
  persons: mockPersons.slice(0, 2),
  episodes: mockEpisodes.slice(0, 1),
  crossReferences: [
    {
      id: 'cr1',
      referenceText: 'Колесниченко Д.А., действуя совместно с Сидоровым В.П...',
      referenceType: 'упоминание',
      sourceDocument: mockDocuments[0],
      targetDocument: mockDocuments[1],
    },
  ],
}
